[package]
name = "dust-lang-wasm"
version = "0.0.10"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
dust-core = { path = "../dust-core" }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.5.0"
